AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda to do HTTP GET
Parameters:
  functionName:
    Description: The name of the lambda function
    Type: String
    MinLength: 1
    MaxLength: 30
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Ref: functionName
      Architectures:
        - x86_64
      MemorySize: 128
      PackageType: Zip
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: function
      Description: A GET function
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
      Layers:
        - Ref: libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: package-layer
      Description: Python packages used by the lambda.
      ContentUri: package
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.10
