name: pydocstyle

on: [push]

jobs:
  pydocstyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Prepare test environment
      uses: ./.github/actions/prepare-test-environment
    - name: pydocstyle
      run: python -m pydocstyle function/*.py --ignore=D107,D203,D213
